language: node_js
node_js:
  - "5.0.0"
script:
  - mkdir -p images
  - cd images
  - curl --compressed -OOOOOOOOOO https://copy.sh/v86/images/{linux.iso,linux3.iso,kolibri.img,windows101.img,os8.dsk,freedos722.img,openbsd.img,oberon.dsk,oberon-boot.dsk}
  - cd ..
  - make build/libv86.js
  - npm test
